package br.com.solsystem.enums;

public enum Permissao {
    PRODUTO_LER,
    PRODUTO_GERENCIAR,
    ESTOQUE_LER,
    ESTOQUE_AJUSTAR,
    VENDA_CRIAR,
    VENDA_CANCELAR,
    CAIXA_OPERAR,
    CAIXA_FECHAR,
    CLIENTE_LER,
    CLIENTE_GERENCIAR,
    CREDIARIO_CONCEDER,
    CREDIARIO_RECEBER,
    RELATORIO_VER,
    FUNCIONARIO_GERENCIAR,
    USUARIO_GERENCIAR,
    AUDITORIA_VER
}
